### ISSUE TITLE
DbSessionExtensions DyUpdate是否可以考虑支持ExpandoObject或HashTable?

### ISSUE THREAD

**Issue by bryanli2018** [dotnetcore/SmartSql#102]
场景是这样，从前台传过来的json使用JsonConvert.DeserializeObject转换后，调用DyUpdate出错。
var str = "{ \"UserID\": \"00000000-0000-0000-0000-000000000000\",\"UserName\": \"管理员\",\"UserCode\":\"admin\",\"UserAccount\":\"admin\"}";
object model = JsonConvert.DeserializeObject<dynamic>(str);
sqlMapper.SessionStore.Open().DyUpdate<TEntity>(model);

**Comment by Ahoo-Wang** [comment]
目前是支持字典类型的。

**Comment by bryanli2018** [comment]
请问有使用示例吗？为什么我传入Dictionary型参数会报Exception如下 : 

◢ | $exception | {"Common Language Runtime detected an invalid program."} | System.InvalidProgramException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2146233030 | int
  | HelpLink | null | string
  | ▶ InnerException | null | System.Exception
  | Message | "Common Language Runtime detected an invalid program." | string
  | Source | "System.Private.CoreLib" | string
  | StackTrace | "   at SmartSql.Reflection.RequestConvert.ToSqlParameters(Object sourceObj, Boolean ignoreNameCase) in E:\\Study\\SmartSql-master\\src\\SmartSql\\Reflection\\RequestConvert.cs:line 18\r\n   at SmartSql.DbSessionExtensions.DyUpdate[TEntity](IDbSession dbSession, Object entity) in E:\\Study\\SmartSql-master\\src\\SmartSql\\CUD\\DbSessionExtensions.cs:line 179\r\n   at SmartSql.ISqlMapperExtensions.DyUpdate[TEntity](ISqlMapper sqlMapper, Object entity) in E:\\Study\\SmartSql-master\\src\\SmartSql\\CUD\\ISqlMapperExtensions.cs:line 23\r\n   at MyTest.Program.DyUpdate() in E:\\Study\\SmartSql-master\\MyTest\\Program.cs:line 143\r\n   at MyTest.Program.Main(String[] args) in E:\\Study\\SmartSql-master\\MyTest\\Program.cs:line 26" | string
  | ▶ TargetSite | {SmartSql.Data.SqlParameterCollection ToSqlParameters(System.Object, Boolean)} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | ▶ Static members |   |  
  | ▶ Non-Public members |   |

**Comment by Ahoo-Wang** [comment]
更新一下版本。v4.1.26 刚刚发布。

**Comment by bryanli2018** [comment]
可以了，谢谢！
