### ISSUE TITLE
性能恶化对处方式

### ISSUE THREAD

**Issue by wangbiglei** [dotnetcore/SmartSql#107]
SQL Server中，Table上字段型是varchar的场合，若使用Parameter传入变数时，内部使用用nvarchar进行比较，性能会恶化。
https://blogs.msdn.microsoft.com/jpsql/2013/06/25/dosdonts-18-net-framework-124/

SmartSql中，对SQL文的参数指定类型和位数是如何设定设置的?

**Comment by Ahoo-Wang** [comment]
可以通过TypeHandler的方式处理。
