### ISSUE TITLE
支持多数据库在部署的时候确定是使用MySql、SqlServer或者Oracle等数据库

### ISSUE THREAD

**Issue by ghd258** [dotnetcore/SmartSql#109]
支持同一个产品，由于客户不同要求使用不同的数据库比如MySql、SqlServer或者Oracle，尽可能的减少写sql语句配置文件

**Comment by Ahoo-Wang** [comment]
可以使用 Env 标签来支持。

**Comment by ghd258** [comment]
1. 抽象出相同的SqlMap里边的SQL
2. 根据Env标签抽离不同DB的方言，比如分页
3. 使用 $ 通配符前缀
4. 使用 环境变量来指定使用哪个 SmartSqlConfig 文件 / ConfigPath 路径写到 appsetting里边 / 部署时手动修改 SmartSqlConfig 文件里边的DBProvider
