### ISSUE TITLE
从连接字符串创建SmartSql实例怎么指定xml路径

### ISSUE THREAD

**Issue by HugoChanD** [dotnetcore/SmartSql#115]
## SmartSql version 4.9.4

var smartSqlBuilder = new SmartSqlBuilder()
    .UseDataSource(DbProvider.SQLSERVER, ConnectionString)
    .Build();

怎么指定xml路径 用SmartSqlMapConfig可以指定SmartSqlMaps标签 如果用上面方式创建如何指定具体的xml

**Comment by Ahoo-Wang** [comment]
https://github.com/dotnetcore/SmartSql/blob/master/src/SmartSql/SmartSqlBuilder.cs#L457

**Comment by HugoChanD** [comment]
指定之后一直找不到Scope
