### ISSUE TITLE
AOP事物里使用IDictionary传参数查询会报Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by chnzhang** [dotnetcore/SmartSql#121]
## Steps to reproduce
![image](https://user-images.githubusercontent.com/3386915/69032529-aa8b4180-0a17-11ea-9551-27897fff2aa9.png)

## Expected result
Common Language Runtime detected an invalid program
## Stack trace

Common Language Runtime detected an invalid program

我改为使用new{}的方式传参数，无问题

这个问题只在AOP事物里有，其他查询没有该问题

**Comment by chnzhang** [comment]
另外我是忽略了大小写的，所以参数大小写没关系

**Comment by chnzhang** [comment]
[EREBUS_Demo.zip](https://github.com/dotnetcore/SmartSql/files/3863162/EREBUS_Demo.zip)
详细说明，在文件的说明文档里

**Comment by Ahoo-Wang** [comment]
![image](https://user-images.githubusercontent.com/4384159/69142156-2e6d2880-0b01-11ea-959e-556fabe581e1.png)
这里必须是 IDictionary<string, Object>
