### ISSUE TITLE
关于Transaction的用法的疑惑

### ISSUE THREAD

**Issue by xclw2000** [dotnetcore/SmartSql#131]
我在Service里写了下面的方法
[Transaction]
        public virtual void MultiInsert()
        {
            // 第一个插入操作
           ...
           // 第二个插入操作
          ...
          // 第N个插入操作
         ...
        }

然后故意让中间某个操作出错，结果发现之前的操作是执行成功的。像这种情况应该怎么使用事务呢？
如果AOP事务只是面向单一操作，那单一操作本身是不是就已经包含事务了，这AOP事务的作用体现在哪里呢

**Comment by Ahoo-Wang** [comment]
https://github.com/dotnetcore/SmartSql/blob/master/sample/SmartSql.Sample.AspNetCore/Startup.cs#L73
