### ISSUE TITLE
How to config more than two same properties in one Statement?

### ISSUE THREAD

**Issue by xy00869474** [dotnetcore/SmartSql#137]
## SmartSql version
4.1.56
## Database provider and version
mysql
## Steps to reproduce
![图片](https://user-images.githubusercontent.com/34831236/88033165-959c1a80-cb71-11ea-9803-caed825134f7.png)
<Statement Id="GetPrototypeConsignStorageDocumentListAsync" ResultMap="PrototypeConsignStorageResultMap">
      select storage_type,a.r3_sales_office,a.r3_sales_channel,a.product_group,a.factory_code,a.customer_code,a.customer_name,
      a.material_code,a.material_name,a.batch_code,instorage_num,used_num,
      (select sum(b.in_out_type*b.quantity) from erp_material_document b
      where b.specific_sign="W" and b.modify_time>=?EndTime and b.modify_user_name="接口调用"
      and a.r3_sales_office = b.r3_sales_office
      and a.product_group = b.product_group
      and (a.r3_sales_channel = b.r3_sales_channel or a.r3_sales_channel="empty")
      and a.specific_sign=b.specific_sign
      and a.factory_code=b.factory_code
      and a.customer_code=b.customer_code
      and a.material_key=b.material_key ) as org_id
      from prototype_consign_storage a where
      a.factory_code!="4030" and a.storage_type=?StorageType
      <IsNotEmpty Prepend=""  Property="CustomerCodeWithOutR3SalesChannelList">
        <IsEmpty Prepend="And" property="CustomerCodeWithR3SalesChannelList">
          (a.main_customer_code + "-" + a.r3_sales_office) in ?CustomerCodeWithOutR3SalesChannelList
        </IsEmpty>
      </IsNotEmpty>
      <IsNotEmpty Prepend=""  Property="CustomerCodeWithR3SalesChannelList">
        <IsEmpty Prepend="And" property="CustomerCodeWithOutR3SalesChannelList">
          (a.main_customer_code + "-" + a.r3_sales_office + "-" + a.r3_sales_channel) in ?CustomerCodeWithR3SalesChannelList
        </IsEmpty>
      </IsNotEmpty>
      <IsNotEmpty Prepend=""   Property="CustomerCodeWithOutR3SalesChannelList">
        <IsNotEmpty Prepend="And" Property="CustomerCodeWithR3SalesChannelList">
          (concat(a.main_customer_code , "-" , a.r3_sales_office) in ?CustomerCodeWithOutR3SalesChannelList or concat(a.main_customer_code , "-" , a.r3_sales_office , "-" , a.r3_sales_channel) in ?CustomerCodeWithR3SalesChannelList)
        </IsNotEmpty>
      </IsNotEmpty>
      <Switch Prepend="Order By" Property="OrderBy">
        <Default>
          a.id Desc
        </Default>
      </Switch>
    </Statement>
## Expected result
SmartSql.Exceptions.SmartSqlException: can not find [Property] from xml-node -> BaseURI:[file:///D:/work/TIMC/01_SourceCode/Hx.Timc.OpenRest.PrototypeStorage/src/05.Api/Hx.Timc.OpenRest.PrototypeStorage.WebApi/bin/Debug/netcoreapp3.1/Maps/PrototypeConsignStorage.xml],[OuterXml]:[<IsEmpty Prepend="And" property="CustomerCodeWithR3SalesChannelList" xmlns="http://SmartSql.net/schemas/SmartSqlMap.xsd">
          (a.main_customer_code + "-" + a.r3_sales_office) in ?CustomerCodeWithOutR3SalesChannelList
        </IsEmpty>].

**Comment by Ahoo-Wang** [comment]
![image](https://user-images.githubusercontent.com/4384159/100745334-18838a80-341a-11eb-93aa-276eea6abbe0.png)
你这个单词写错了，首字母变成了小写。
建议：通过Nuget 安装 SmartSql.Schema 获得智能提示，这样会这种坑爹的错误，参见 https://smartsql.net/guide/getting-started.html 。

![image](https://user-images.githubusercontent.com/4384159/100745558-67c9bb00-341a-11eb-8184-cfa9b34159d4.png)
