### ISSUE TITLE
升级到net5

### ISSUE THREAD

**Issue by ghd258** [dotnetcore/SmartSql#144]
升级到net5

**Comment by Ahoo-Wang** [comment]
暂时还没有对.NET 5 进行兼容性测试，如果方便的话你可以提交一个不兼容的测试报告吗？

**Comment by ghd258** [comment]
3.1升级到5.0非常平滑，只是修改下 <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

**Comment by XiaoHeitu** [comment]
做过单元测试几乎完全通过，但有一个 存储过程，我这里没有，可以提供一下吗？

` Could not find stored procedure 'SP_QueryUser'.`

**Comment by XiaoHeitu** [comment]
找到了。
`CREATE PROCEDURE [dbo].[SP_QueryUser] @Total INT = 0 Out AS BEGIN	
	SET NOCOUNT ON;	
	SET @Total = ( SELECT COUNT ( * ) FROM T_User T WITH ( NoLock ) );
	SELECT TOP
		10 T.* 
	FROM
	T_User T WITH ( NoLock ) 
END`

**Comment by XiaoHeitu** [comment]
.NET 5 环境下，全部通过！

![image](https://user-images.githubusercontent.com/38452227/101110885-f99d1800-3614-11eb-94d2-6b605eadf893.png)

**Comment by ghd258** [comment]
5.0的性能比3.1高了吗

**Comment by XiaoHeitu** [comment]
没详细测试。目测有一定的性能提升。
