### ISSUE TITLE
select * 报错，改为select id,name.... 全部列名就没事

### ISSUE THREAD

**Issue by KillingMeNow** [dotnetcore/SmartSql#149]
{"Exception of type 'System.ExecutionEngineException' was thrown."}  System.ExecutionEngineException
报错信息很短 也看不出什么信息
是不支持select * 吗

**Comment by Ahoo-Wang** [comment]
@KillingMeNow 请提供完整的代码，以及报错内容。

**Comment by Ahoo-Wang** [comment]
太久没有回复。
