### ISSUE TITLE
建议将DbProvider的配置放到配置文件中

### ISSUE THREAD

**Issue by xiangxiren** [dotnetcore/SmartSql#151]
当前：新增数据库支持是通过修改`DbProvider`和`DbProvider`

建议：从xml配置文件中读取，我记得以前IBatis.Net有个providers.xml配置文件

这样就不用去修改代码

**Comment by Ahoo-Wang** [comment]
现在也不需要修改代码呀。
因为 DbProvider 相对来说是比较稳定的，所以硬编码到代码层面了，所以我们我也不需要自己维护 providers。这样其实更方便了，只要写一个 DbProvider 名称就可以了。

**Comment by xiangxiren** [comment]
之前帮一个群友对接人大金仓数据库，就得在DbProvider里去添加东西。如果是通过配置文件配置，就不需要修改源码。

**Comment by Ahoo-Wang** [comment]
为什么需要修改源码啊？

**Comment by Ahoo-Wang** [comment]
https://smartsql.net/config/#database-%E5%AD%90%E6%A0%87%E7%AD%BE
![image](https://user-images.githubusercontent.com/4384159/120574828-8ef95780-c452-11eb-9b2f-91a7c47f9df9.png)
![image](https://user-images.githubusercontent.com/4384159/120574844-9a4c8300-c452-11eb-8181-4b55e24bcbba.png)
直接填上这个就可以啦。

**Comment by xiangxiren** [comment]
<DbProvider Name="SQLite"/>
这里的Name的值是不是得DbProvider.cs定义的常量里存在
https://github.com/dotnetcore/SmartSql/blob/cbc9c45416141429fac8793cfda7e60c7067d09c/src/SmartSql/DataSource/DbProvider.cs#L10-L17

同时DbProviderManager.cs里定义的常量存在对应的DbProvider 
https://github.com/dotnetcore/SmartSql/blob/cbc9c45416141429fac8793cfda7e60c7067d09c/src/SmartSql/DataSource/DbProviderManager.cs#L13-L66

**Comment by Ahoo-Wang** [comment]
![image](https://user-images.githubusercontent.com/4384159/120576465-62930a80-c455-11eb-9cad-5a20b3363156.png)
你可以直接定义 Type 的。

**Comment by Ahoo-Wang** [comment]
你是不是没有安装 
[SmartSql.Schema](https://www.nuget.org/packages/SmartSql.Schema/)，所以没有看到智能提示？

**Comment by xiangxiren** [comment]
明白了……

**Comment by xiangxiren** [comment]
> 你是不是没有安装
> [SmartSql.Schema](https://www.nuget.org/packages/SmartSql.Schema/)，所以没有看到智能提示？

装了啊，有提示。但这个地方一般就想着设置一个Name。认为对应的Type都是在代码里定义好了的。

**Comment by Ahoo-Wang** [comment]
应用还有人跟你有相同的问题，有兴趣的话可以一起参与一下文档共建。https://github.com/Smart-Kit/SmartSql-Docs

**Comment by xiangxiren** [comment]
ok

**Comment by Ahoo-Wang** [comment]
> ok

没啥其他问题的话就把issue关掉吧。
