### ISSUE TITLE
Oracle 中的union all  语句 smartsql不支持，请帮忙看下。

### ISSUE THREAD

**Issue by LiuweiILoveYouDanDan** [dotnetcore/SmartSql#154]
Oracle 中的union all  语句 smartsql不支持，请帮忙看下。
xml中的sql语句，直接复制到db执行工具中可以执行的，但是代码中是无法执行，总是报错“并非所有变量都已绑定”。
急急急。

**Comment by Ahoo-Wang** [comment]
https://github.com/dotnetcore/SmartSql/releases/tag/v4.1.19
试一下这个。

**Comment by Ahoo-Wang** [comment]
#89 跟这个issue应该是一样的问题。

**Comment by LiuweiILoveYouDanDan** [comment]
虎哥，还是不行，我尝试用#89的解决方案，但是行不通。

**Comment by Ahoo-Wang** [comment]
@LiuweiILoveYouDanDan 解决了没？
