### ISSUE TITLE
DyRepository是否支持.NET Framework 4.6版本？

### ISSUE THREAD

**Issue by LambertW** [dotnetcore/SmartSql#39]
如题，若支持，麻烦给出Demo演示。

目前在Starter项目中，仅看到.Net standard方式的注入。

在.NET framework 4.6版本中又该如何实现？

**Comment by ElderJames** [comment]
支持，使用 MapperContainer.Instance.GetSqlMapper() 获取ISmartSqlMapper实例。
当然IoC注册还没支持MSDI以外的框架。有这方面的需求需要根据SmartSql.DIExtension这个项目去注册SamrtSql相关组件。

**Comment by z514987467** [comment]
.NET Framework 4.6怎么用
