### ISSUE TITLE
SmartSql-Roadmap-2019

### ISSUE THREAD

**Issue by Ahoo-Wang** [dotnetcore/SmartSql#47]
# SmartSql Roadmap - 2019

> Simplicity, efficiency, performance, scalability, monitoring, progressive development

---

> 简洁、高效、性能、扩展性、监控、渐进式开发

## Q2 - SmartSql-V4

- Execute flow refactoring (pipeline-middleware mode)
- Increase unit Test coverage
- Increase performance test report granularity and coverage
- IDataReaderDeserializer
  - DictionaryDeserializer
  - DynamicDeserializer
  - EntityDeserializer
  - MultipleResultDeserializer
  - ValueTypeDeserializer
- Custom Tags
  - Script Tag
- TypeHandler refactoring
- CUD Auto Implementation (configuration Entity.tablename required)
- Dynamic Prxy Repository Refactoring
- Multi-configuration Source loader support
  - XmlConfigLoader
    - File
    - Embedded
  - JsonConfigLoader
  - ZookeeperConfigLoader
  - ConsulConfigLoader
- Minimize the running environment(only DataSource)
- Distributed Cache Refactoring
- Diagnostics support
  - Cache
  - PreparedStatement
  - CommandExecuter
  - Deserializer
  - ERROR
- DI Use experience optimization
- SmartSql.Batch -> SmartSql.Bulk
- IdGenerator

---

- 执行流重构（管道-中间件模式）
- 增加单元测试覆盖率
- 增加性能测试报告粒度与覆盖率
- IDataReaderDeserializer
  - DictionaryDeserializer
  - DynamicDeserializer
  - EntityDeserializer
  - MultipleResultDeserializer
  - ValueTypeDeserializer
- 自定义标签
  - Script Tag
- TypeHandler 重构
- CUD 自动实现 (需配置Entity.TableName)
- 动态代理仓储重构
- 多配置源加载器支持
  - XmlConfigLoader
    - File
    - Embedded
  - JsonConfigLoader
  - ZookeeperConfigLoader
  - ConsulConfigLoader
- 最小化可运行环境（only DataSource）
- 分布式缓存重构
- Diagnostics 支持
  - Cache
  - PreparedStatement
  - CommandExecuter
  - Deserializer
  - ERROR
- DI 使用体验优化
- SmartSql.Batch -> SmartSql.Bulk
- IdGenerator

## Q3

- SmartExpression (<https://github.com/Smart-Kit/SmartExpression>)
- SmartSql
  - Public configuration
  - Expression attribute support
  - Expression tag support
- Wiki

---

- SmartExpression (<https://github.com/Smart-Kit/SmartExpression>)
- SmartSql
  - 公共配置
  - 表达式属性支持
  - 表达式标签支持
- Wiki

## Q4

- SmartSql.Monitor
  - Authorized
  - Performance
  - Fault Tracking
  - Call Trace
  - Dynamic configuration
  - UI
  - Storage
    - InMemory
    - ...

---

- SmartSql.Monitor
  - 授权
  - 性能监控
  - 故障跟踪
  - 调用跟踪
  - 动态配置
  - UI
  - 存储
    - InMemory
    - ...

**Comment by Ahoo-Wang** [comment]
![image](https://user-images.githubusercontent.com/4384159/55884718-1cc2ba80-5bdb-11e9-936e-2db7b3acc4f1.png)

**Comment by lksong110** [comment]
虎哥.........VVVVVVV5
