### ISSUE TITLE
Incorrect redirect of english document on main page.

### ISSUE THREAD

**Issue by lujiaxing** [dotnetcore/SmartSql#61]
![image](https://user-images.githubusercontent.com/7188738/56115751-b650ea00-5f96-11e9-8516-086478cf2def.png)

This link navigates to a url and then automaticlly redirected to chinese homepage of this project.

**Comment by Ahoo-Wang** [comment]
@lujiaxing Thank you for submitting the issue. I'm currently working on a V4 version of the document. I'll fix this later.

**Comment by Ahoo-Wang** [comment]
fix rel https://smartsql.net/en/
