### ISSUE TITLE
接口上的 Transaction 特性无效

### ISSUE THREAD

**Issue by Seanwong933** [dotnetcore/SmartSql#62]
在虚方法上这个特性有效，在接口方法上无效：
请问是不支持接口吗？

有效示例：
```C#
[Transaction]
public virtual async Task<bool> UpdateAsync(ArticleUpdateParameter parameter)
{
     var externalTask = SetArticleTagsAndCategories(parameter.Id, parameter.Tags, parameter.Categories);
     var updateTask = ArticleRepository.UpdateAsync(parameter);
     await Task.WhenAll(externalTask, updateTask);
     return true;
}
```
![image](https://user-images.githubusercontent.com/11625599/56217626-21cdb100-6096-11e9-8608-4e76305caf5f.png)

无效示例：
```C#
[Transaction]
Task<int> DeleteAsync(int id);
```
![image](https://user-images.githubusercontent.com/11625599/56217762-59d4f400-6096-11e9-9e11-69a37cba1e77.png)

**Comment by Ahoo-Wang** [comment]
1. 代理仓储接口从使用上应该是不需要加事务AOP注解的，因为这个是单一操作，不需要加事务。
2. 代理仓储接口是通过SmartSql的动态代理库动态生成的实现类，而SmartSql.AOP提供的事务AOP注解是通过 [AspectCore-Framework](https://github.com/dotnetcore/AspectCore-Framework) 来提供的，这就相当于 动态代理 + 动态代理。

**Comment by Seanwong933** [comment]
明白了 ，谢谢解答
不过我的`Delete`里有五条语句，所以才想这样操作的。
现在声明了个虚方法加上`Transaction`实现了。

**Comment by Ahoo-Wang** [comment]
@Seanwong933 下个小版本将支持
![image](https://user-images.githubusercontent.com/4384159/56355628-5ada6280-6209-11e9-9218-7540f0f77777.png)

**Comment by Seanwong933** [comment]
点赞~

**Comment by Ahoo-Wang** [comment]
Ref https://github.com/dotnetcore/SmartSql/releases/tag/v4.0.29

可以通过一下几种方式开启事物:
1. 在动态仓储接口函数上加上 UseTransaction 注解
``` csharp
        [UseTransaction]
        long DoByAnnotationTransaction(AllPrimitive entity);
```
2. 在 Statement 加上 Transaction 属性
``` xml
 <Statement Id="DoByTransaction" Transaction="Unspecified">
// do-something-0 
// do-something-1
// do-something-2 
// do-something-3 
</Statement>
```
3.  在 RequestContext 传入 Transaction 属性

``` csharp
            var id = DbSession.ExecuteScalar<long>(new RequestContext
            {
                Scope = nameof(User),
                SqlId = "Insert",
                Transaction = IsolationLevel.Unspecified,
                Request = new User
                {
                   UserName= "SmartSql",
                }
            });
```

**Comment by Seanwong933** [comment]
谢谢，用上了~
