### ISSUE TITLE
建议 有木有计划支持存储过程

### ISSUE THREAD

**Issue by Microshaoft** [dotnetcore/SmartSql#65]

**Comment by Ahoo-Wang** [comment]
@Microshaoft SmartSql 一直都是支持存储过程的。
https://smartsql.net/guide/getting-started.html#storedprocedure

**Comment by Microshaoft** [comment]
不好意思，我意思是，通过配置的方式。另外免实体类，从而进一步免c#后续编程，例如，通过配置实现webapi执行存储过程，请求参数，应答参数都是json
