### ISSUE TITLE
希望支持CommitTransaction(Action commitAction)重载方法

### ISSUE THREAD

**Issue by aqqxiejian** [dotnetcore/SmartSql#73]
![image](https://user-images.githubusercontent.com/13502753/59585833-f574f600-9113-11e9-90a5-a9016a82cd85.png)
因为我在使用CAP时（https://github.com/dotnetcore/CAP） CAP的事务提交方法内部执行了Flush() 方法，SmartSql在提交事务的时候也执行了其他的事件，这样我就不能单方面以CAP或者SmartSql来提交事务（或者有什么更好的解决方案呢？）， 所以我希望在SmartSql提交事务时支持委托方法，由方法外部来确认。

**Comment by ElderJames** [comment]
可自己实现smartsql的这个接口。

https://github.com/dotnetcore/SmartSql/blob/777fad815c9b9f0115f10a30446d405cf72f0b57/src/SmartSql/DbSession/ITransaction.cs#L6
