### ISSUE TITLE
表描述中存在换行符时, 不能正常生成对应的实体类描述(XML注释)

### ISSUE THREAD

**Issue by lybing** [dotnetcore/SmartSql#75]
当表描述中包含换行符，比如：
EXEC sp_addextendedproperty N'MS_Description', N'线路表
记录线路的名称，创建者等等', 'SCHEMA', N'dbo', 'TABLE', N'MS20_Route', NULL, NULL

生成对应的实体类为：
namespace SmartSql.Starter.Entity
{
    ///<summary>
    ///线路表
记录线路的名称，创建者等
    ///</summary>
    public class MS20Route
    {    }
}

**Comment by Ahoo-Wang** [comment]
请到 SmartCode - > https://github.com/dotnetcore/SmartCode/issues 重新提交该issue
