### ISSUE TITLE
好是好，不过配置太复杂，文档不详细；就算要配置mysql都找不到案例还有看源码才知道怎么配置

### ISSUE THREAD

**Issue by yangQingYu123** [dotnetcore/SmartSql#76]
好是好，不过配置太复杂，文档不详细；就算要配置mysql都找不到案例还有看源码才知道怎么配置

**Comment by ElderJames** [comment]
文档缺少的不分可以提出来

**Comment by yangQingYu123** [comment]
您好！smartcode支持codefirst吗

**Comment by Ahoo-Wang** [comment]
@yangQingYu123 暂时没有计划支持CodeFirst,如果希望获得CodeFirst体验，建议使用EF。
1. 请把你认为的文档不详细的地方提出来，一起完善。
----
SmartSql -> ORM
SmartCode -> 代码生成器 + ETL工具。
