### ISSUE TITLE
mysql blob类型的字段 select后报Buffer index must be a valid index in buffer错误

### ISSUE THREAD

**Issue by xflag** [dotnetcore/SmartSql#77]
mysql里blob字段，存''字符串，select到实体报Buffer index must be a valid index in buffer，希望修复一下此问题。

**Comment by Ahoo-Wang** [comment]
贴一下复现代码。

**Comment by xflag** [comment]
> 贴一下复现代码。

C#对应字段用byte[]类型，用动态代理仓储模式，GetEntityAsync方法，获取单个对象，报上述错误。
当blob存''时会报错，有数据则不会。
同样的数据，我用dapper获取，也是用byte[]类型接收，则不会报错，正常获取成功。
