### ISSUE TITLE
rediscache get请求时用int[]方式，缓存有bug

### ISSUE THREAD

**Issue by xflag** [dotnetcore/SmartSql#79]
`
 [HttpGet("Query")]
public async Task<ResponseResultModel<IEnumerable<A>>> GetQueryAsync([FromQuery]int[] id)
`
对应的SqlMap配置
`
<Statement Id="Query" ResultMap="A"  Cache="A.RedisCache">
`

在测试时，
int[]先传[1,2]，返回两条记录
再传null，返回全部记录
再传[3]，最后的[3]就会直接返回第2次传null时写入的redis缓存，本来应该返回一条记录，但却返回了全部记录

**Comment by Ahoo-Wang** [comment]
代码贴多点。

**Comment by xflag** [comment]
> 代码贴多点。

`
[HttpGet("Query")] public async Task<ResponseResultModel<IEnumerable<A>>> GetQueryAsync([FromQuery]int[] id)
{
var list = await _aRepository.QueryAsync(new
            {
                Ids = id                
            });//动态仓储模式调用
//其它代码
}
`

`
<Statement Id="QueryParams">
      <Where>       
        <IsNotEmpty Prepend="And" Property="Ids">
          T.id IN ?Ids
        </IsNotEmpty>        
      </Where>
    </Statement>
<Statement Id="Query" ResultMap="A">
      SELECT T.* From table_a T
      <Include RefId="QueryParams" />      
    </Statement>
`

大致代码如上

**Comment by Ahoo-Wang** [comment]
更新到 v4.1.0 试一下

**Comment by xflag** [comment]
> 更新到 v4.1.0 试一下

tks，已解决
