### ISSUE TITLE
执行多个参数的sql语句，oracle提示错误 ORA-01008: 并非所有变量都已绑定

### ISSUE THREAD

**Issue by Wscar** [dotnetcore/SmartSql#89]

**Comment by GandalfGao** [comment]
请问一下这个command.BindByName = true;中的command是什么数据类型啊？？？

**Comment by GandalfGao** [comment]
还有它是怎么去调用设置？在SmartSql上？

**Comment by Ahoo-Wang** [comment]
https://github.com/dotnetcore/SmartSql/blob/master/src/SmartSql.Oracle/SmartSqlBuilderExtensions.cs

**Comment by GandalfGao** [comment]
您知道这是为什么吗？如果您知道还请指教一二多谢

**Comment by GandalfGao** [comment]
对了，我的环境是.Net5

**Comment by GandalfGao** [comment]
我已经找到该方法了，谢谢，我先试试看看

**Comment by GandalfGao** [comment]
我试了下是好使的，刚才不好意思，我看了源码，看到他们命名空间一样就以为是在一个类库下，结果他们不是，我的疏忽
