### ISSUE TITLE
SqlMap的Scope中有特殊符号“."时，会加载不到sql

### ISSUE THREAD

**Issue by bryanli2018** [dotnetcore/SmartSql#91]
<SmartSqlMap Scope="BSM.User" xmlns="http://SmartSql.net/schemas/SmartSqlMap.xsd">
Scope 中有个" . ",同时使用 <Include RefId="QueryParams" />时，会报异常信息”ConfigLoader can not find SqlMap.Scoe:BSM“

**Comment by Ahoo-Wang** [comment]
Scope 里边是不可以有【.】的。

**Comment by bryanli2018** [comment]
了解，谢谢！
