### ISSUE TITLE
请问支持全局过滤器和多租户么？

### ISSUE THREAD

**Issue by liugt34** [dotnetcore/SmartSql#96]
请问大神，有没有类似EF的HasQueryFilter方法或配置呢，这样就可以支持多租户了？
如果不支持有没有什么好的代替方式呢？

**Comment by Ahoo-Wang** [comment]
https://github.com/dotnetcore/SmartSql/blob/master/src/SmartSql.Test.Unit/SmartSqlFixture.cs#L31
