### ISSUE TITLE
IIdGenerator的NextId方法是long型的，请问怎么定义Guid类型的Id

### ISSUE THREAD

**Issue by liugt34** [dotnetcore/SmartSql#98]
之前的数据库Id全部使用的Guid类型，看文档上自定义Id的接口IIdGenerator，结果实现NextId方法必须返回Guid，请问大神怎么解决这个问题？

**Comment by Ahoo-Wang** [comment]
那就忽略吧，不需要用内置ID生成器了。

**Comment by Ahoo-Wang** [comment]
![image](https://user-images.githubusercontent.com/4384159/63832161-ca741180-c9a2-11e9-8f88-aee8bca4496c.png)
https://github.com/dotnetcore/SmartSql/blob/master/src/SmartSql/Configuration/Tags/UUID.cs#L14



使用UUID 标签。
