### ISSUE TITLE
MultipleResultMap不支持异步么？

### ISSUE THREAD

**Issue by liugt34** [dotnetcore/SmartSql#99]
Demo里面的分页
[Statement(Id = "QueryByPage")]
TPageResult GetByPage<TPageResult>(object request);

改成Task<TPageResult> GetByPage<TPageResult>(object request); 就无法查询到数据了

**Comment by Ahoo-Wang** [comment]
支持。贴复现代码。以及异常堆栈。

**Comment by liugt34** [comment]
在SmartSql.Sample.AspNetCore那个Demo项目里面
1：修改接口 IUserRepository第20行为
`Task<TPageResult> GetByPage<TPageResult>(object request);`
2：UserController.cs里面第64行
`
[HttpGet]
        public async Task<GetByPageResponse<User>> GetByPage(int pageIndex = 1)
        {
            return await _userRepository.GetByPage<GetByPageResponse<User>>(new
            {
                PageSize = 10,
                PageIndex = pageIndex
            });
        }
`
swagger测试返回结构
`
{
  "list": null,
  "total": 0
}
`

**Comment by Ahoo-Wang** [comment]
已确认是bug,马上修复发版。
